# Generated by Django 6.0.1 on 2026-01-27 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('product_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='产品类型')),
                ('demand', models.TextField(blank=True, null=True, verbose_name='需求描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('is_handled', models.BooleanField(default=False, verbose_name='是否已处理')),
            ],
            options={
                'verbose_name': '联系表单',
                'verbose_name_plural': '联系表单',
                'ordering': ['-created_at'],
            },
        ),
    ]
